### PR TITLE
Equisplit

### PR DESCRIPTION
**Pull request by alexandremkuhn**
Following a previous pull request (https://github.com/lawremi/VariantTools/pull/1), Michael Lawrence suggested to add an equisplit function (named epGRanges in the previous PR) to GenomicRanges (instead of VariantTools).

Proposed changes include an equisplit generic in  S4Vectors, an equisplit function (for GenomicRanges objects) in GenomicRanges and minor changes in VariantTools to accommodate param@bamTallyParam@which as GRangesList (in addition to GenomicRanges).

### CODE REVIEW

**Comment by alexandremkuhn** [comment]
Hi Michael @lawremi, do you think it is fine to add these changes to VariantTools now that there is an equisplit method available for GenomicRanges objects?

**Comment by lawremi** [comment]
Have you verified that this patch works with the current devel S4Vectors, etc?

**Comment by alexandremkuhn** [comment]
Yes I did.

**Comment by lawremi** [comment]
Cool, thanks for the contribution.

**Pull request merged**
